coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto

codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no